In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
b = np.argmax(a)
b

0

In [ ]:
c = np.argmax(a[0])
c

0

In [ ]:
a = [[0,1,0],[0,1,0]]
a

[[0, 1, 0], [0, 1, 0]]

In [ ]:
c = np.argmax(a[0])
c

1

In [1]:
a = [[0,1,2],[10,11,12]]
a

[[0, 1, 2], [10, 11, 12]]

In [2]:
import numpy as np

In [3]:
a.shape

AttributeError: 'list' object has no attribute 'shape'

In [4]:
np.shape(a)

(2, 3)

In [5]:
maxtest = [1,1,1,1,1,0,0,0,0,0,1]
np.argmax(maxtest)

0

In [7]:
np.argmax(np.array(maxtest))

0

In [8]:
oneslist = np.ones((2,3))
oneslist

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.argmax(oneslist)

0

In [10]:
np.argmax(oneslist, axis=0)

array([0, 0, 0])

In [11]:
np.argmax(oneslist, axis=1)

array([0, 0])

In [12]:
oneslist [0][1] = 2
oneslist

array([[1., 2., 1.],
       [1., 1., 1.]])

In [13]:
np.argmax(oneslist, axis=0)

array([0, 0, 0])

In [14]:
np.argmax(oneslist, axis=1)

array([1, 0])

In [15]:
np.argmax(oneslist[0], axis=0)

1

In [16]:
np.argmax(maxtest[0])

0

In [17]:
maxtest = np.array([1,1,1,1,1,0,0,0,0,0,1])
np.argmax(maxtest[0])

0

In [18]:
maxtest

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1])

In [19]:
oneslist

array([[1., 2., 1.],
       [1., 1., 1.]])

In [20]:
oneslist[0][1] = 0
oneslist

array([[1., 0., 1.],
       [1., 1., 1.]])

In [21]:
np.argmax(oneslist[0], axis=0)

0

In [22]:
def find_max_indices(arr):
    max_val = np.max(arr)
    max_indices = np.where(arr == max_val)[0]
    return max_indices

# Example usage
arr = np.array([3, 5, 2, 8, 8, 1, 4])
result = find_max_indices(arr)
print(result)


[3 4]


In [26]:
zerolist = np.zeros((2,3))
zerolist[0][2] = 1
zerolist

array([[0., 0., 1.],
       [0., 0., 0.]])

In [27]:
np.argmax(zerolist)

2